### ISSUE TITLE
Add extension for EnergyModelsGUI for variable descriptions

### ISSUE THREAD

**Issue by Zetison** [EnergyModelsX/EnergyModelsHeat.jl#6]
To get rid of warnings when running the graphical user interface using EnergyModelsGUI together with EnergyModelsHeat and to provide descriptive names to the variables in the GUI you should add a file `descriptive_names.yml` in a folder called `EMGUIExt` which must be located in a folder `ext` of the `EnergyModelsHeat` repository. As only `TimeProfile`s (and JuMP variables with a time dimension) are plotted, only these fields need provided descriptions. The `descriptive_names.yml` looks something like
```yml
# This file contains descriptions of EnergyModelsHeat-structures and variables 
# with fields of type TimeStruct.TimeProfile
structures:
  HeatPump:
    cap:                    "Installed capacity"
    t_source:               "Temperature profile of the heat source"
    t_sink:                 "Sink temperature of the condensator"
    eff_carnot:             "Carnot Efficiency"
    opex_var:               "Variable operating expense per energy unit produced"
    opex_fixed:             "Fixed operating expense per installed capacity"
  ResourceHeat:
    t_supply:               "Supply temperature in °C"
    t_return:               "Return temperature in °C"
  DHPipe:
    cap:                    "Heat transport capacity of the pipe"
    t_ground:               "Ground temperature in °C"
  HeatExchanger:
    cap:                    "Installed capacity"
    opex_var:               "Variable operating expense per energy unit produced"
    opex_fixed:             "Fixed operating expense"
  DirectHeatUpgrade:
    cap:                    "Installed capacity"
    opex_var:               "Variable operating expense per energy unit produced"
    opex_fixed:             "Fixed operating expense"

# Add description for all JuMP variables using a TimeStruct.TimeProfile type
variables:
  dh_pipe_loss:             "Heat losses in DH pipes"
```
Note that this requires EnergyModelsGUI v0.5.11 or higher.
